name: Build BungeeCord JAR

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # 直接 checkout 你的仓库
      with:
        fetch-depth: 0  # 拉取完整 Git 历史（可选）

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'  # 使用 Eclipse Temurin JDK

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package -DfinalName=bungeecord -Dcheckstyle.skip=true

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bungeecord.jar
        path: target/bungeecord.jar  # 根据你的构建输出路径调整
