name: Build BungeeCord JAR

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: md-5/BungeeCord
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with custom Maven command
      run: mvn clean package -DfinalName=bungeecord -Dcheckstyle.skip=true

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: bungeecord.jar
        path: target/bungeecord.jar
